<a href="https://colab.research.google.com/github/Krrish-P12/EDA/blob/main/EDALab-Assessment1_25BAI0030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/chess_games.csv",encoding = 'latin1')

#Displays the last 5 rows of the dataframe
display(df.tail())

#Displays the first 6 rows of the dataframe
display(df.head(6))

print("Info and description of the dataframe\n");
df.info() #gives the data type of the rows and column entities
df.describe() #gives various details like central tendencies etc

winner_stats = df['winner'].value_counts()
print(winner_stats)

print("\nLong games count\n")
long_games = df[df['turns'] > 100]
display(long_games.head())

#prints the rating difference
df['rating_difference'] = abs(df['white_rating'] - df['black_rating'])
display(df.head())

# Average turns by winner
avgturnswinner = df.groupby('winner')['turns'].mean()
print(avgturnswinner)

# Sorting the DataFrame by turns in descending order
print(" Sorted Data: Turns in Descending Order\n")
dfsorted = df.sort_values(by='turns', ascending=False)
display(dfsorted.head())

#New column total_rating by summing white and black ratings
print("Data with New Column: Total Rating\n")
df['total_rating'] = df['white_rating'] + df['black_rating']
display(df.head())

# Counting the number of games for each opening using value counts
print("Value Counts: Top 5 Opening Full Names\n")
opening_counts = df['opening_fullname'].value_counts()
print(opening_counts.head())

#Showing top 6 games with Queen's Gambit
print("Games with Caro-Kann Opening\n")
QG = df[df['opening_fullname'] == "Queen's Gambit"]
display(QG.head(6))

Mounted at /content/drive

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
20053,20054,True,24,Resign,White,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,2,Dutch Defense,Dutch Defense,NaN,NaN
20054,20055,True,82,Mate,Black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,2,Queen's Pawn,Queen's Pawn,NaN,NaN
20055,20056,True,35,Mate,White,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
20056,20057,True,109,Resign,White,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20057,20058,True,78,Mate,Black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN
5,6,False,5,Draw,Draw,10+0,trelynn17,1250,franklin14532,1002,e4 c5 Nf3 Qa5 a3,B27,4,Sicilian Defense: Mongoose Variation,Sicilian Defense,NaN,Mongoose Variation

Info and description of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            20058 non-null  int64
 1   rated              20058 non-null  bool
 2   turns              20058 non-null  int64
 3   victory_status     20058 non-null  object
 4   winner             20058 non-null  object
 5   time_increment     20058 non-null  object
 6   white_id           20058 non-null  object
 7   white_rating       20058 non-null  int64
 8   black_id           20058 non-null  object
 9   black_rating       20058 non-null  int64
 10  moves              20058 non-null  object
 11  opening_code       20058 non-null  object
 12  opening_moves      20058 non-null  int64
 13  opening_fullname   20058 non-null  object
 14  opening_shortname  20058 non-null  object
 15  opening_response   1207 non-null   object
 16  opening_variation  14398 non-null  object
dtypes: bool(1), int64(5), object(11)
memory usage: 2.5+ MB
winner
White    10001
Black     9107
Draw       950
Name: count, dtype: int64

Long games count

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
9,10,True,119,Mate,White,10+0,daniel_likes_chess,1381,mirco25,1209,e4 d5 exd5 Qxd5 Nc3 Qe5+ Be2 Na6 d4 Qf5 Bxa6 b...,B01,4,Scandinavian Defense: Mieses-Kotroc Variation,Scandinavian Defense,NaN,Mieses-Kotroc Variation
18,19,False,101,Resign,Black,15+15,shivangithegenius,1094,slam_ment,1300,e4 e5 Nf3 d6 Bc4 Be6 d3 Bxc4 dxc4 c5 O-O h6 Nc...,C41,5,Philidor Defense #3,Philidor Defense,NaN,#3
76,77,True,131,Resign,White,30+0,oldpaths,1571,tb-123,1728,d4 Nf6 Bf4 d5 Nf3 e6 c4 Bd6 Bg3 Bxg3 hxg3 h6 N...,D02,5,Queen's Pawn Game: London System,Queen's Pawn Game,NaN,London System
85,86,True,114,Resign,White,15+5,oldpaths,1522,matheuswillx,1512,d4 c6 Bf4 e6 Nf3 d5 Nbd2 c5 e3 cxd4 Nxd4 a6 c4...,A40,1,Queen's Pawn,Queen's Pawn,NaN,NaN
98,99,True,113,Draw,Draw,15+0,avelez8,1745,anonymous1705,1714,d4 d5 c4 Nf6 Nc3 Bf5 Bf4 a6 Nf3 e6 a3 Nc6 e3 B...,D06,4,Queen's Gambit Refused: Marshall Defense,Queen's Gambit,Refused,Marshall Defense

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation,rating_difference
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation,309
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation,61
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation,4
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation,15
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN,54

winner
Black    60.724388
Draw     86.157895
White    57.790221
Name: turns, dtype: float64
 Sorted Data: Turns in Descending Order

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation,rating_difference
13859,13860,True,349,Out of Time,White,10+0,shiwen,2194,kijek,2240,d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 Bg5 h6 Bxf6 Qxf6 Qb...,D30,13,Queen's Gambit Declined: Hastings Variation,Queen's Gambit,Declined,Hastings Variation,46
11554,11555,True,349,Out of Time,White,10+0,shiwen,2194,kijek,2240,d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 Bg5 h6 Bxf6 Qxf6 Qb...,D30,13,Queen's Gambit Declined: Hastings Variation,Queen's Gambit,Declined,Hastings Variation,46
16386,16387,True,259,Draw,Draw,15+5,aragon26,1441,lone-wolf,1461,d4 d5 c4 c6 Nc3 Nf6 Bg5 Nbd7 Qc2 Qb6 e3 h6 Bf4...,D10,5,Slav Defense #2,Slav Defense,NaN,#2,20
4236,4237,True,255,Draw,Draw,7+2,manipin,1585,kasparovd0311,1448,e4 e6 Nc3 d5 exd5 exd5 d4 Nf6 Bf4 Be7 Nf3 O-O ...,C00,3,French Defense: Queen's Knight,French Defense,NaN,Queen's Knight,137
16645,16646,True,226,Draw,Draw,10+0,chunnev,1817,jhonthoth,1907,e4 e6 Nf3 d5 exd5 exd5 d4 Nf6 Bg5 Be7 Nc3 Be6 ...,C00,3,French Defense: Knight Variation,French Defense,NaN,Knight Variation,90

Data with New Column: Total Rating

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation,rating_difference,total_rating
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation,309,2691
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation,61,2583
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation,4,2996
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation,15,2893
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN,54,2992

Value Counts: Top 5 Opening Full Names

opening_fullname
Van't Kruijs Opening                368
Sicilian Defense                    358
Sicilian Defense: Bowdler Attack    296
French Defense: Knight Variation    271
Scotch Game                         271
Name: count, dtype: int64
Games with Caro-Kann Opening

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation,rating_difference,total_rating
1700,1701,True,31,Mate,White,10+0,kuanxxx,1682,crax_is_bax,1670,d4 d5 c4 b6 Nc3 dxc4 e4 f5 e5 e6 Bxc4 Bb7 Nf3 ...,D06,3,Queen's Gambit,Queen's Gambit,NaN,NaN,12,3352
1704,1705,True,41,Resign,White,10+0,chessnickname,1799,crax_is_bax,1711,d4 d5 c4 b6 Nc3 dxc4 Bf4 f6 e3 g5 Bg3 Bb7 Qh5+...,D06,3,Queen's Gambit,Queen's Gambit,NaN,NaN,88,3510
3436,3437,True,42,Mate,Black,10+0,butledge,1278,tsarmaxamar,1357,d4 d5 c4 g6 Nf3 Nc6 a4 dxc4 e3 e5 b3 exd4 bxc4...,D06,3,Queen's Gambit,Queen's Gambit,NaN,NaN,79,2635
5962,5963,False,24,Resign,White,20+15,releasethebats,2156,rng2016,1220,d4 d5 c4 f6 cxd5 Qxd5 Nc3 Qa5 e4 e5 dxe5 fxe5 ...,D06,3,Queen's Gambit,Queen's Gambit,NaN,NaN,936,3376
6134,6135,False,65,Mate,White,30+0,triskorg,1738,carson_wells,1364,d4 d5 c4 Be6 cxd5 Bxd5 Nc3 c6 e4 Be6 Nf3 Bg4 B...,D06,3,Queen's Gambit,Queen's Gambit,NaN,NaN,374,3102
6146,6147,True,3,Resign,White,25+3,nuffsaidm8,1560,andrewjiang,1160,d4 d5 c4,D06,3,Queen's Gambit,Queen's Gambit,NaN,NaN,400,2720