<a href="https://colab.research.google.com/github/Krrish-P12/EDA/blob/main/EDALab_Assessment_2_25BAI0030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

df_students = pd.DataFrame({
    'StudentID': [56, 2, 3, 4, 5],
    'FirstName': ['Krrish', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'LastName': ['P', 'Johnson', 'Brown', 'Davis', 'Miller'],
    'Major': ['AI', 'Physics', 'Mathematics', 'Chemistry', 'Biology'],
    'EntryYear': [2025, 2020, 2022, 2021, 2023],
    'GPA': [9.2, 7.9, 9.1, 7.3, 8.8]
})

print("Initial df_students:")
display(df_students)

students1 = pd.DataFrame({
    'StudentID': [51, 52, 55],
    'FirstName': ['Uma', 'Dhanush', 'Rohit'],
    'LastName': ['Rani', 'Iyer', 'Kumar'],
    'Major': ['Physics', 'Art', 'Math'],
    'EntryYear': [2024, 2023, 2025],
    'GPA': [7.1, 8.5, 8.4]
})

#created randoom datasets

students2 = pd.DataFrame({
    'StudentID': [53, 54, 56],
    'FirstName': ['Walter', 'Chahal', 'Krrish'],
    'LastName': ['White', 'Singh', 'P'],
    'Major': ['Chemistry', 'History', 'AI'],
    'EntryYear': [2022, 2024, 2025],
    'GPA': [9.2, 7.9, 9.2]
})

# Concatenate the new student dataframes (part 1 and part 2) together
all_new_students = pd.concat([students1, students2], ignore_index = True)
#assigns new indices to elements

print("Concatenated new student records:")
display(all_new_students)

# Using an 'outer' merge on 'StudentID' to include all students from both DataFrames
updated_df1 = pd.merge(df_students, all_new_students, on='StudentID', how='outer')
updated_df2 = pd.merge(df_students, all_new_students, on='FirstName', how='inner') #using inner to merge dataframes according to First Name

# Display the updated df_students DataFrame

print("\nOriginal df_students head:")
display(df_students.head())

print("\nUpdated df_students (after merging new students) tail:")
display(updated_df1.tail())
display(updated_df2.tail())

Initial df_students:

   StudentID FirstName LastName        Major  EntryYear  GPA
0         56    Krrish        P           AI       2025  9.2
1          2       Bob  Johnson      Physics       2020  7.9
2          3   Charlie    Brown  Mathematics       2022  9.1
3          4     Diana    Davis    Chemistry       2021  7.3
4          5       Eve   Miller      Biology       2023  8.8

Concatenated new student records:

   StudentID FirstName LastName      Major  EntryYear  GPA
0         51       Uma     Rani    Physics       2024  7.1
1         52   Dhanush     Iyer        Art       2023  8.5
2         55     Rohit    Kumar       Math       2025  8.4
3         53    Walter    White  Chemistry       2022  9.2
4         54    Chahal    Singh    History       2024  7.9
5         56    Krrish        P         AI       2025  9.2

Original df_students head:

   StudentID FirstName LastName        Major  EntryYear  GPA
0         56    Krrish        P           AI       2025  9.2
1          2       Bob  Johnson      Physics       2020  7.9
2          3   Charlie    Brown  Mathematics       2022  9.1
3          4     Diana    Davis    Chemistry       2021  7.3
4          5       Eve   Miller      Biology       2023  8.8

Updated df_students (after merging new students) tail:

,StudentID,FirstName_x,LastName_x,Major_x,EntryYear_x,GPA_x,FirstName_y,LastName_y,Major_y,EntryYear_y,GPA_y
5,52,NaN,NaN,NaN,NaN,NaN,Dhanush,Iyer,Art,2023.0,8.5
6,53,NaN,NaN,NaN,NaN,NaN,Walter,White,Chemistry,2022.0,9.2
7,54,NaN,NaN,NaN,NaN,NaN,Chahal,Singh,History,2024.0,7.9
8,55,NaN,NaN,NaN,NaN,NaN,Rohit,Kumar,Math,2025.0,8.4
9,56,Krrish,P,AI,2025.0,9.2,Krrish,P,AI,2025.0,9.2

,StudentID_x,FirstName,LastName_x,Major_x,EntryYear_x,GPA_x,StudentID_y,LastName_y,Major_y,EntryYear_y,GPA_y
0,56,Krrish,P,AI,2025,9.2,56.0,P,AI,2025.0,9.2
1,2,Bob,Johnson,Physics,2020,7.9,NaN,NaN,NaN,NaN,NaN
2,3,Charlie,Brown,Mathematics,2022,9.1,NaN,NaN,NaN,NaN,NaN
3,4,Diana,Davis,Chemistry,2021,7.3,NaN,NaN,NaN,NaN,NaN
4,5,Eve,Miller,Biology,2023,8.8,NaN,NaN,NaN,NaN,NaN

In [6]:
import pandas as pd
import numpy as np

data_example = {'CityA': [10, 20], 'CityB': [15, 25]}
df_example = pd.DataFrame(data_example, index=['Temp', 'Humidity'])
print("Original DataFrame (df_example):")
display(df_example)

stacked_series = df_example.stack()
print("\nStacked Series:")
display(stacked_series)

unstacked_df = stacked_series.unstack()
print("\nUnstacked DataFrame:")
display(unstacked_df)


# Create two simple Series
series_one = pd.Series([100, 200], index=['Item1', 'Item2'])
series_two = pd.Series([300, 400], index=['Item3', 'Item4'])

print("Series One:")
display(series_one)
print("\nSeries Two:")
display(series_two)

# 3. pd.concat() with keysCreate a hierarchical index
concatenated_with_keys = pd.concat([series_one, series_two], keys=['Dataset_X', 'Dataset_Y'])
print("\nConcatenated Series with hierarchical index:\n")
display(concatenated_with_keys)

unstacked = concatenated_with_keys.unstack()
print("Unstacked Concatenated Series (showing how keys would become columns):")
display(unstacked)

Original DataFrame (df_example):

          CityA  CityB
Temp         10     15
Humidity     20     25

Stacked Series:

Temp      CityA    10
          CityB    15
Humidity  CityA    20
          CityB    25
dtype: int64

Unstacked DataFrame:

          CityA  CityB
Temp         10     15
Humidity     20     25

Series One:

Item1    100
Item2    200
dtype: int64

Series Two:

Item3    300
Item4    400
dtype: int64

Concatenated Series with hierarchical index:

Dataset_X  Item1    100
           Item2    200
Dataset_Y  Item3    300
           Item4    400
dtype: int64

Unstacked Concatenated Series (showing how keys would become columns):

           Item1  Item2  Item3  Item4
Dataset_X  100.0  200.0    NaN    NaN
Dataset_Y    NaN    NaN  300.0  400.0